### ISSUE TITLE
Correction proposal of welcome message

### ISSUE THREAD

**Issue by Krusty27** [TheAngryPython/tg-diary#1]
Hi, I just wanted to notice you that _'Hi! I bot a diary with encryption. No one except you will not be able to read the text.'_ contains 2 errors. 

I think _'Hi! I **am** bot a diary with encryption. No one except you will ~~not~~ be able to read the text.'_ should be better.

**Comment by TheAngryPython** [comment]
Hello! Thank you. The translator Yandex was used for translation so errors are inevitable. This text was also translated with it.
